# Cargo-deny configuration for mTLS Proxy
# This file configures dependency checking, security scanning, and licensing

[advisories]
# Check for security advisories
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
    # Add any advisories to ignore here
]

[licenses]
# License checking configuration
confidence-threshold = 0.8

# Allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    "Zlib",
    "Unicode-3.0",
]

# License exceptions (for specific crates)
exceptions = [
    # Add any exceptions here if needed
    # { name = "some-crate", allow = ["MIT"] },
]

[bans]
# Dependency banning configuration
multiple-versions = "warn"

# Banned dependencies
deny = [
    # Add any banned dependencies here
]

# Skip specific dependencies from checks
skip = [
    # Add any dependencies to skip here
]
