# Cargo-deny configuration for mTLS Proxy
# This file configures dependency checking, security scanning, and licensing

[advisories]
# Check for security advisories
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
yanked = "warn"
ignore = [
    # Add any advisories to ignore here
]

[licenses]
# License checking configuration
default = "deny"
copyleft = "deny"
allow-osi-fsf-free = "both"
confidence-threshold = 0.8
clarify = true
expression-spdx = true

# Allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0",
    "Unlicense",
    "Zlib",
    "OpenSSL",
]

# Explicitly denied licenses
deny = [
    "GPL-1.0",
    "GPL-1.0+",
    "GPL-2.0",
    "GPL-2.0+",
    "GPL-2.0-only",
    "GPL-2.0-or-later",
    "GPL-3.0",
    "GPL-3.0+",
    "GPL-3.0-only",
    "GPL-3.0-or-later",
    "AGPL-1.0",
    "AGPL-1.0+",
    "AGPL-3.0",
    "AGPL-3.0+",
    "AGPL-3.0-only",
    "AGPL-3.0-or-later",
    "LGPL-2.0",
    "LGPL-2.0+",
    "LGPL-2.1",
    "LGPL-2.1+",
    "LGPL-3.0",
    "LGPL-3.0+",
]

# License exceptions (for specific crates)
exceptions = [
    # Add any exceptions here if needed
    # { name = "some-crate", allow = ["MIT"] },
]

[source]
# Source registry configuration
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = []

[source."https://github.com/rust-lang/crates.io-index"]
replace-with = "crates-io"

[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

# Git sources (if any)
[source."https://github.com/your-org/private-registry"]
registry = "https://github.com/your-org/private-registry"

[target.'cfg(all())']
# Target-specific configuration
allow = [
    "MIT",
    "Apache-2.0",
]

[target.'cfg(windows)']
# Windows-specific configuration
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
]

[target.'cfg(unix)']
# Unix-specific configuration
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
]
