[server]
host = "127.0.0.1"
port = 8444
max_connections = 1000

[tls]
cert_path = "certs/server.crt"
key_path = "certs/server.key"
ca_cert_path = "certs/ca.crt"
require_client_cert = true

[responses]
default_delay_ms = 100
error_rate_percent = 0
streaming_enabled = true
max_tokens = 1000
temperature = 0.7

[models]
available = ["gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo"]
