# Local configuration overrides
# This file is not committed to version control

[server]
# host = "0.0.0.0"  # Uncomment to bind to all interfaces
# port = 8444

[tls]
# cert_path = "certs/server.crt"
# key_path = "certs/server.key"
# ca_cert_path = "certs/ca.crt"
# require_client_cert = true

[responses]
# default_delay_ms = 100
# error_rate_percent = 0
# streaming_enabled = true

[models]
# available = ["gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo"]
